# Generated by Django 5.1 on 2024-08-31 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.IntegerField()),
                ('re_Enter_Password', models.IntegerField()),
                ('confirm_Password', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='addCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='addClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('shop_name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='invoiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(default='Unknown Supplier', max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('invoice_number', models.IntegerField()),
                ('qty', models.IntegerField(default=0)),
                ('rate', models.IntegerField()),
                ('gst_percentage', models.DecimalField(decimal_places=2, help_text='GST percentage', max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amound', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mrp', models.IntegerField()),
                ('select_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.addcategories')),
                ('select_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='clientSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('mrp', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sales', to='myapp.addclient')),
                ('select_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.addcategories')),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_sales', to='myapp.addclient')),
                ('select_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
            ],
        ),
    ]
