# Generated by Django 5.1 on 2024-09-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_client_name_clientsales_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsales',
            name='client',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clientsales',
            name='select_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clientsales',
            name='select_product',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clientsales',
            name='shop',
            field=models.CharField(max_length=50),
        ),
    ]
