# Generated by Django 5.1 on 2024-09-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_clientsales_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('mobile', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('select_category', models.CharField(max_length=100)),
                ('select_product', models.CharField(max_length=100)),
                ('mrp', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
