# Generated by Django 5.1 on 2024-09-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_customersales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceentry',
            name='select_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invoiceentry',
            name='select_product',
            field=models.CharField(max_length=50),
        ),
    ]
